hyperparameters:
  # Training
  train_dataset_name: ['offenseval']
  test_dataset_name: ['offenseval']
  model_type: ['BasicLSTM']
  optimizer_type: ['adam']
  loss_criterion: ['bcelosswithlogits']
  lr: [0.001]
  epochs: [10]
  batch_size: [64]
  patience_es: [5]

  # Scheduler
  scheduler_type: ['']
  patience_lr: [3]

  # Saving condition by acc or loss
  save_condition: ['acc']

  # Misc.
  fix_length: [null]
